# Generated by Django 3.2.15 on 2022-08-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_place_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
