# Generated by Django 3.2.15 on 2022-08-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(verbose_name='datepublished'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subhead',
            field=models.TextField(),
        ),
    ]
